name: Zig Tests

on:
  push:
    branches:
      - main # Change this to your branch name if needed
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Zig
        run: |
          curl -LO https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar -xf zig-linux-x86_64-0.13.0.tar.xz
          mv zig-linux-x86_64-0.13.0 zig

      - name: Run Zig tests
        run: ./zig/zig build test --summary all
